// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	inscripcion_evento "github.com/MervanXD/backend_ClubYa/internal/models/inscripcion_evento"
	mock "github.com/stretchr/testify/mock"
)

// InscripcionEventoRepository is an autogenerated mock type for the InscripcionEventoRepository type
type InscripcionEventoRepository struct {
	mock.Mock
}

// ObtenerEventosSocio provides a mock function with given fields: idSocio
func (_m *InscripcionEventoRepository) ObtenerEventosSocio(idSocio int) ([]inscripcion_evento.InscripcionSocioDTO, error) {
	ret := _m.Called(idSocio)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerEventosSocio")
	}

	var r0 []inscripcion_evento.InscripcionSocioDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]inscripcion_evento.InscripcionSocioDTO, error)); ok {
		return rf(idSocio)
	}
	if rf, ok := ret.Get(0).(func(int) []inscripcion_evento.InscripcionSocioDTO); ok {
		r0 = rf(idSocio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]inscripcion_evento.InscripcionSocioDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idSocio)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistrarInscripcion provides a mock function with given fields: fidPersona, idEvento, cantidadInvitados
func (_m *InscripcionEventoRepository) RegistrarInscripcion(fidPersona int, idEvento int, cantidadInvitados int) error {
	ret := _m.Called(fidPersona, idEvento, cantidadInvitados)

	if len(ret) == 0 {
		panic("no return value specified for RegistrarInscripcion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, int) error); ok {
		r0 = rf(fidPersona, idEvento, cantidadInvitados)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInscripcionEventoRepository creates a new instance of InscripcionEventoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInscripcionEventoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InscripcionEventoRepository {
	mock := &InscripcionEventoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
