// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	detalledisponibilidad "github.com/MervanXD/backend_ClubYa/internal/models/detalle_disponibilidad"
	mock "github.com/stretchr/testify/mock"
)

// DetalleDisponibilidadRepository is an autogenerated mock type for the DetalleDisponibilidadRepository type
type DetalleDisponibilidadRepository struct {
	mock.Mock
}

// ActualizarEstadoDetalleDisponibilidad provides a mock function with given fields: idHorarioDia, idBloqueTiempo, estado
func (_m *DetalleDisponibilidadRepository) ActualizarEstadoDetalleDisponibilidad(idHorarioDia int, idBloqueTiempo int, estado string) error {
	ret := _m.Called(idHorarioDia, idBloqueTiempo, estado)

	if len(ret) == 0 {
		panic("no return value specified for ActualizarEstadoDetalleDisponibilidad")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, string) error); ok {
		r0 = rf(idHorarioDia, idBloqueTiempo, estado)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ObtenerDisponibilidadEspacioSocialPorId provides a mock function with given fields: ctx, idEspacio, idHorarioDia, idBloqueTiempo
func (_m *DetalleDisponibilidadRepository) ObtenerDisponibilidadEspacioSocialPorId(ctx context.Context, idEspacio int, idHorarioDia int, idBloqueTiempo int) (*detalledisponibilidad.DisponibilidadEspacioResponse, error) {
	ret := _m.Called(ctx, idEspacio, idHorarioDia, idBloqueTiempo)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerDisponibilidadEspacioSocialPorId")
	}

	var r0 *detalledisponibilidad.DisponibilidadEspacioResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) (*detalledisponibilidad.DisponibilidadEspacioResponse, error)); ok {
		return rf(ctx, idEspacio, idHorarioDia, idBloqueTiempo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) *detalledisponibilidad.DisponibilidadEspacioResponse); ok {
		r0 = rf(ctx, idEspacio, idHorarioDia, idBloqueTiempo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*detalledisponibilidad.DisponibilidadEspacioResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, idEspacio, idHorarioDia, idBloqueTiempo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDetalleDisponibilidadRepository creates a new instance of DetalleDisponibilidadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDetalleDisponibilidadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DetalleDisponibilidadRepository {
	mock := &DetalleDisponibilidadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
