// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	espacio "github.com/MervanXD/backend_ClubYa/internal/models/espacio"
	mock "github.com/stretchr/testify/mock"
)

// CanchaRepository is an autogenerated mock type for the CanchaRepository type
type CanchaRepository struct {
	mock.Mock
}

// ActualizarParcial provides a mock function with given fields: id, dto
func (_m *CanchaRepository) ActualizarParcial(id int, dto espacio.CanchaUpdateDTO) error {
	ret := _m.Called(id, dto)

	if len(ret) == 0 {
		panic("no return value specified for ActualizarParcial")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, espacio.CanchaUpdateDTO) error); ok {
		r0 = rf(id, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertarCancha provides a mock function with given fields: c
func (_m *CanchaRepository) InsertarCancha(c espacio.Cancha) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for InsertarCancha")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(espacio.Cancha) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ObtenerCanchasHorarios provides a mock function with no fields
func (_m *CanchaRepository) ObtenerCanchasHorarios() ([]espacio.CanchaHorarioDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ObtenerCanchasHorarios")
	}

	var r0 []espacio.CanchaHorarioDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]espacio.CanchaHorarioDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []espacio.CanchaHorarioDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]espacio.CanchaHorarioDTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCanchaRepository creates a new instance of CanchaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCanchaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CanchaRepository {
	mock := &CanchaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
