// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	espacio "github.com/MervanXD/backend_ClubYa/internal/models/espacio"
	mock "github.com/stretchr/testify/mock"
)

// EspacioSocialRepository is an autogenerated mock type for the EspacioSocialRepository type
type EspacioSocialRepository struct {
	mock.Mock
}

// InsertarEspacioSocial provides a mock function with given fields: es
func (_m *EspacioSocialRepository) InsertarEspacioSocial(es espacio.EspacioSocial) error {
	ret := _m.Called(es)

	if len(ret) == 0 {
		panic("no return value specified for InsertarEspacioSocial")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(espacio.EspacioSocial) error); ok {
		r0 = rf(es)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ObtenerEspacioSocialPorID provides a mock function with given fields: ctx, id
func (_m *EspacioSocialRepository) ObtenerEspacioSocialPorID(ctx context.Context, id int) (*espacio.EspacioSocial, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerEspacioSocialPorID")
	}

	var r0 *espacio.EspacioSocial
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*espacio.EspacioSocial, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *espacio.EspacioSocial); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*espacio.EspacioSocial)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObtenerEspaciosSociales provides a mock function with no fields
func (_m *EspacioSocialRepository) ObtenerEspaciosSociales() ([]espacio.EspacioSocial, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ObtenerEspaciosSociales")
	}

	var r0 []espacio.EspacioSocial
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]espacio.EspacioSocial, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []espacio.EspacioSocial); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]espacio.EspacioSocial)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObtenerEspaciosSocialesHorarios provides a mock function with no fields
func (_m *EspacioSocialRepository) ObtenerEspaciosSocialesHorarios() ([]espacio.EspacioSocialHorarioDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ObtenerEspaciosSocialesHorarios")
	}

	var r0 []espacio.EspacioSocialHorarioDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]espacio.EspacioSocialHorarioDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []espacio.EspacioSocialHorarioDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]espacio.EspacioSocialHorarioDTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEspacioSocialRepository creates a new instance of EspacioSocialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEspacioSocialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EspacioSocialRepository {
	mock := &EspacioSocialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
