// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	inscripcionacademia "github.com/MervanXD/backend_ClubYa/internal/models/inscripcion_academia"
	mock "github.com/stretchr/testify/mock"
)

// InscripcionAcademiaRepository is an autogenerated mock type for the InscripcionAcademiaRepository type
type InscripcionAcademiaRepository struct {
	mock.Mock
}

// ObtenerFamiliaresInscritosAcademia provides a mock function with given fields: idSocio
func (_m *InscripcionAcademiaRepository) ObtenerFamiliaresInscritosAcademia(idSocio int) ([]inscripcionacademia.InscritoAcademiaDTO, error) {
	ret := _m.Called(idSocio)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerFamiliaresInscritosAcademia")
	}

	var r0 []inscripcionacademia.InscritoAcademiaDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]inscripcionacademia.InscritoAcademiaDTO, error)); ok {
		return rf(idSocio)
	}
	if rf, ok := ret.Get(0).(func(int) []inscripcionacademia.InscritoAcademiaDTO); ok {
		r0 = rf(idSocio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]inscripcionacademia.InscritoAcademiaDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idSocio)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistrarInscripcionAcademia provides a mock function with given fields: idPersonaint, idGrupo, idTarifa, uniforme, costo_total
func (_m *InscripcionAcademiaRepository) RegistrarInscripcionAcademia(idPersonaint int, idGrupo int, idTarifa int, uniforme int, costo_total float64) error {
	ret := _m.Called(idPersonaint, idGrupo, idTarifa, uniforme, costo_total)

	if len(ret) == 0 {
		panic("no return value specified for RegistrarInscripcionAcademia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, int, int, float64) error); ok {
		r0 = rf(idPersonaint, idGrupo, idTarifa, uniforme, costo_total)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInscripcionAcademiaRepository creates a new instance of InscripcionAcademiaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInscripcionAcademiaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InscripcionAcademiaRepository {
	mock := &InscripcionAcademiaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
