// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	persona "github.com/MervanXD/backend_ClubYa/internal/models/persona"
	solicitud "github.com/MervanXD/backend_ClubYa/internal/models/solicitud_membresia"
	mock "github.com/stretchr/testify/mock"
)

// SolicitudRepository is an autogenerated mock type for the SolicitudRepository type
type SolicitudRepository struct {
	mock.Mock
}

// ActualizarEstadoSolicitud provides a mock function with given fields: id, nuevoEstado
func (_m *SolicitudRepository) ActualizarEstadoSolicitud(id int, nuevoEstado string) error {
	ret := _m.Called(id, nuevoEstado)

	if len(ret) == 0 {
		panic("no return value specified for ActualizarEstadoSolicitud")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(id, nuevoEstado)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ObtenerDatosPersonaPorIdSolicitud provides a mock function with given fields: idSolicitud
func (_m *SolicitudRepository) ObtenerDatosPersonaPorIdSolicitud(idSolicitud int) (*persona.Titular, error) {
	ret := _m.Called(idSolicitud)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerDatosPersonaPorIdSolicitud")
	}

	var r0 *persona.Titular
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*persona.Titular, error)); ok {
		return rf(idSolicitud)
	}
	if rf, ok := ret.Get(0).(func(int) *persona.Titular); ok {
		r0 = rf(idSolicitud)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persona.Titular)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idSolicitud)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObtenerDatosSolicitudPorId provides a mock function with given fields: idSolicitud
func (_m *SolicitudRepository) ObtenerDatosSolicitudPorId(idSolicitud int) (*solicitud.SolicitudMembresia, error) {
	ret := _m.Called(idSolicitud)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerDatosSolicitudPorId")
	}

	var r0 *solicitud.SolicitudMembresia
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*solicitud.SolicitudMembresia, error)); ok {
		return rf(idSolicitud)
	}
	if rf, ok := ret.Get(0).(func(int) *solicitud.SolicitudMembresia); ok {
		r0 = rf(idSolicitud)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*solicitud.SolicitudMembresia)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idSolicitud)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObtenerEstadoSolicitudPorID provides a mock function with given fields: idSolicitud
func (_m *SolicitudRepository) ObtenerEstadoSolicitudPorID(idSolicitud int) (string, error) {
	ret := _m.Called(idSolicitud)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerEstadoSolicitudPorID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(idSolicitud)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(idSolicitud)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idSolicitud)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObtenerFamiliaresPorIdSolicitud provides a mock function with given fields: idSolicitud
func (_m *SolicitudRepository) ObtenerFamiliaresPorIdSolicitud(idSolicitud int) ([]persona.Familiar, error) {
	ret := _m.Called(idSolicitud)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerFamiliaresPorIdSolicitud")
	}

	var r0 []persona.Familiar
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]persona.Familiar, error)); ok {
		return rf(idSolicitud)
	}
	if rf, ok := ret.Get(0).(func(int) []persona.Familiar); ok {
		r0 = rf(idSolicitud)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]persona.Familiar)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idSolicitud)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObtenerSolicitudesMembresia provides a mock function with no fields
func (_m *SolicitudRepository) ObtenerSolicitudesMembresia() ([]solicitud.SolicitudDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ObtenerSolicitudesMembresia")
	}

	var r0 []solicitud.SolicitudDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]solicitud.SolicitudDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []solicitud.SolicitudDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]solicitud.SolicitudDTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSolicitudRepository creates a new instance of SolicitudRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSolicitudRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SolicitudRepository {
	mock := &SolicitudRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
