// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	persona "github.com/MervanXD/backend_ClubYa/internal/models/persona"
	mock "github.com/stretchr/testify/mock"
)

// FamiliarRepository is an autogenerated mock type for the FamiliarRepository type
type FamiliarRepository struct {
	mock.Mock
}

// CrearSolicitudRetiro provides a mock function with given fields: idFamiliar, motivo
func (_m *FamiliarRepository) CrearSolicitudRetiro(idFamiliar int, motivo string) error {
	ret := _m.Called(idFamiliar, motivo)

	if len(ret) == 0 {
		panic("no return value specified for CrearSolicitudRetiro")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(idFamiliar, motivo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertarFamiliar provides a mock function with given fields: f, idTitular
func (_m *FamiliarRepository) InsertarFamiliar(f persona.Familiar, idTitular int) error {
	ret := _m.Called(f, idTitular)

	if len(ret) == 0 {
		panic("no return value specified for InsertarFamiliar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(persona.Familiar, int) error); ok {
		r0 = rf(f, idTitular)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ObtenerFamiliarPorIDPersona provides a mock function with given fields: idPersona
func (_m *FamiliarRepository) ObtenerFamiliarPorIDPersona(idPersona int) (*persona.Familiar, error) {
	ret := _m.Called(idPersona)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerFamiliarPorIDPersona")
	}

	var r0 *persona.Familiar
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*persona.Familiar, error)); ok {
		return rf(idPersona)
	}
	if rf, ok := ret.Get(0).(func(int) *persona.Familiar); ok {
		r0 = rf(idPersona)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persona.Familiar)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idPersona)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObtenerIdsFamiliaresPorTitular provides a mock function with given fields: idTitular
func (_m *FamiliarRepository) ObtenerIdsFamiliaresPorTitular(idTitular int) ([]persona.Familiar, error) {
	ret := _m.Called(idTitular)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerIdsFamiliaresPorTitular")
	}

	var r0 []persona.Familiar
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]persona.Familiar, error)); ok {
		return rf(idTitular)
	}
	if rf, ok := ret.Get(0).(func(int) []persona.Familiar); ok {
		r0 = rf(idTitular)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]persona.Familiar)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idTitular)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistrarFamiliarConSolicitud provides a mock function with given fields: f, idTitular
func (_m *FamiliarRepository) RegistrarFamiliarConSolicitud(f persona.Familiar, idTitular int) error {
	ret := _m.Called(f, idTitular)

	if len(ret) == 0 {
		panic("no return value specified for RegistrarFamiliarConSolicitud")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(persona.Familiar, int) error); ok {
		r0 = rf(f, idTitular)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegistrarFamiliares provides a mock function with given fields: req
func (_m *FamiliarRepository) RegistrarFamiliares(req persona.FamiliarResquest) (int, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for RegistrarFamiliares")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(persona.FamiliarResquest) (int, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(persona.FamiliarResquest) int); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(persona.FamiliarResquest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFamiliarRepository creates a new instance of FamiliarRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFamiliarRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FamiliarRepository {
	mock := &FamiliarRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
