// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	persona "github.com/MervanXD/backend_ClubYa/internal/models/persona"
	mock "github.com/stretchr/testify/mock"
)

// TitularRepository is an autogenerated mock type for the TitularRepository type
type TitularRepository struct {
	mock.Mock
}

// InsertarTitular provides a mock function with given fields: p, idCuenta
func (_m *TitularRepository) InsertarTitular(p persona.Titular, idCuenta int) (int, error) {
	ret := _m.Called(p, idCuenta)

	if len(ret) == 0 {
		panic("no return value specified for InsertarTitular")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(persona.Titular, int) (int, error)); ok {
		return rf(p, idCuenta)
	}
	if rf, ok := ret.Get(0).(func(persona.Titular, int) int); ok {
		r0 = rf(p, idCuenta)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(persona.Titular, int) error); ok {
		r1 = rf(p, idCuenta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObtenerTitularPorID provides a mock function with given fields: ctx, idPersona
func (_m *TitularRepository) ObtenerTitularPorID(ctx context.Context, idPersona int) (*persona.Titular, error) {
	ret := _m.Called(ctx, idPersona)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerTitularPorID")
	}

	var r0 *persona.Titular
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*persona.Titular, error)); ok {
		return rf(ctx, idPersona)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *persona.Titular); ok {
		r0 = rf(ctx, idPersona)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persona.Titular)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, idPersona)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTitularRepository creates a new instance of TitularRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTitularRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TitularRepository {
	mock := &TitularRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
