// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	reserva "github.com/MervanXD/backend_ClubYa/internal/models/reserva"
	mock "github.com/stretchr/testify/mock"
)

// ReservaRepository is an autogenerated mock type for the ReservaRepository type
type ReservaRepository struct {
	mock.Mock
}

// AnulacionReservaEspacioSocial provides a mock function with given fields: idReserva, idEspacio, idHorarioDia, idBloque, motivo
func (_m *ReservaRepository) AnulacionReservaEspacioSocial(idReserva int, idEspacio int, idHorarioDia int, idBloque int, motivo string) error {
	ret := _m.Called(idReserva, idEspacio, idHorarioDia, idBloque, motivo)

	if len(ret) == 0 {
		panic("no return value specified for AnulacionReservaEspacioSocial")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, int, int, string) error); ok {
		r0 = rf(idReserva, idEspacio, idHorarioDia, idBloque, motivo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ObtenerReservasCanchasSocio provides a mock function with given fields: idSocio
func (_m *ReservaRepository) ObtenerReservasCanchasSocio(idSocio int) ([]reserva.ReservaCanchaRequest, error) {
	ret := _m.Called(idSocio)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerReservasCanchasSocio")
	}

	var r0 []reserva.ReservaCanchaRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]reserva.ReservaCanchaRequest, error)); ok {
		return rf(idSocio)
	}
	if rf, ok := ret.Get(0).(func(int) []reserva.ReservaCanchaRequest); ok {
		r0 = rf(idSocio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reserva.ReservaCanchaRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idSocio)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObtenerReservasEspaciosSocialesSocio provides a mock function with given fields: idSocio
func (_m *ReservaRepository) ObtenerReservasEspaciosSocialesSocio(idSocio int) ([]reserva.ReservaEspacioSocialRequest, error) {
	ret := _m.Called(idSocio)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerReservasEspaciosSocialesSocio")
	}

	var r0 []reserva.ReservaEspacioSocialRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]reserva.ReservaEspacioSocialRequest, error)); ok {
		return rf(idSocio)
	}
	if rf, ok := ret.Get(0).(func(int) []reserva.ReservaEspacioSocialRequest); ok {
		r0 = rf(idSocio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reserva.ReservaEspacioSocialRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idSocio)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObtenerReservasPorEspacio provides a mock function with given fields: idEspacio
func (_m *ReservaRepository) ObtenerReservasPorEspacio(idEspacio int) ([]reserva.ReservaRequest, error) {
	ret := _m.Called(idEspacio)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerReservasPorEspacio")
	}

	var r0 []reserva.ReservaRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]reserva.ReservaRequest, error)); ok {
		return rf(idEspacio)
	}
	if rf, ok := ret.Get(0).(func(int) []reserva.ReservaRequest); ok {
		r0 = rf(idEspacio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reserva.ReservaRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idEspacio)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReservarEspacio provides a mock function with given fields: idEspacio, idHorarioDia, idBloqueTiempo
func (_m *ReservaRepository) ReservarEspacio(idEspacio int, idHorarioDia int, idBloqueTiempo int) error {
	ret := _m.Called(idEspacio, idHorarioDia, idBloqueTiempo)

	if len(ret) == 0 {
		panic("no return value specified for ReservarEspacio")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, int) error); ok {
		r0 = rf(idEspacio, idHorarioDia, idBloqueTiempo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReservarEspacioSocial provides a mock function with given fields: _a0
func (_m *ReservaRepository) ReservarEspacioSocial(_a0 reserva.ReservaEspacio) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ReservarEspacioSocial")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(reserva.ReservaEspacio) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReservaRepository creates a new instance of ReservaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReservaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReservaRepository {
	mock := &ReservaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
