// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	evento "github.com/MervanXD/backend_ClubYa/internal/models/evento"
	mock "github.com/stretchr/testify/mock"
)

// EventoRepository is an autogenerated mock type for the EventoRepository type
type EventoRepository struct {
	mock.Mock
}

// BuscarEventoPorID provides a mock function with given fields: id
func (_m *EventoRepository) BuscarEventoPorID(id int) (*evento.Evento, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for BuscarEventoPorID")
	}

	var r0 *evento.Evento
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*evento.Evento, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *evento.Evento); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*evento.Evento)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelarEvento provides a mock function with given fields: idEvento
func (_m *EventoRepository) CancelarEvento(idEvento int) error {
	ret := _m.Called(idEvento)

	if len(ret) == 0 {
		panic("no return value specified for CancelarEvento")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(idEvento)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EliminarEvento provides a mock function with given fields: idEvento
func (_m *EventoRepository) EliminarEvento(idEvento int) error {
	ret := _m.Called(idEvento)

	if len(ret) == 0 {
		panic("no return value specified for EliminarEvento")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(idEvento)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertarEvento provides a mock function with given fields: req
func (_m *EventoRepository) InsertarEvento(req evento.EventoRequest) (int, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for InsertarEvento")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(evento.EventoRequest) (int, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(evento.EventoRequest) int); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(evento.EventoRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListarEventos provides a mock function with no fields
func (_m *EventoRepository) ListarEventos() ([]evento.Evento, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListarEventos")
	}

	var r0 []evento.Evento
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]evento.Evento, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []evento.Evento); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]evento.Evento)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ModificarEvento provides a mock function with given fields: req
func (_m *EventoRepository) ModificarEvento(req evento.EventoRequest) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ModificarEvento")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(evento.EventoRequest) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventoRepository creates a new instance of EventoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventoRepository {
	mock := &EventoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
