// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	academia "github.com/MervanXD/backend_ClubYa/internal/models/academia"
	mock "github.com/stretchr/testify/mock"
)

// AcademiaRepository is an autogenerated mock type for the AcademiaRepository type
type AcademiaRepository struct {
	mock.Mock
}

// ObtenerAcademiaPorId provides a mock function with given fields: idAcademia
func (_m *AcademiaRepository) ObtenerAcademiaPorId(idAcademia int) (*academia.Academia, error) {
	ret := _m.Called(idAcademia)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerAcademiaPorId")
	}

	var r0 *academia.Academia
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*academia.Academia, error)); ok {
		return rf(idAcademia)
	}
	if rf, ok := ret.Get(0).(func(int) *academia.Academia); ok {
		r0 = rf(idAcademia)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*academia.Academia)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idAcademia)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObtenerAcademias provides a mock function with no fields
func (_m *AcademiaRepository) ObtenerAcademias() ([]academia.AcademiaDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ObtenerAcademias")
	}

	var r0 []academia.AcademiaDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]academia.AcademiaDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []academia.AcademiaDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]academia.AcademiaDTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAcademiaRepository creates a new instance of AcademiaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAcademiaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AcademiaRepository {
	mock := &AcademiaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
