// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	bloque_tiempo "github.com/MervanXD/backend_ClubYa/internal/models/bloque_tiempo"
	mock "github.com/stretchr/testify/mock"
)

// BloqueTiempoRepository is an autogenerated mock type for the BloqueTiempoRepository type
type BloqueTiempoRepository struct {
	mock.Mock
}

// ObtenerBloquesTiempoEspacio provides a mock function with given fields: idEspacio
func (_m *BloqueTiempoRepository) ObtenerBloquesTiempoEspacio(idEspacio int) ([]bloque_tiempo.BloqueTiempo, error) {
	ret := _m.Called(idEspacio)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerBloquesTiempoEspacio")
	}

	var r0 []bloque_tiempo.BloqueTiempo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]bloque_tiempo.BloqueTiempo, error)); ok {
		return rf(idEspacio)
	}
	if rf, ok := ret.Get(0).(func(int) []bloque_tiempo.BloqueTiempo); ok {
		r0 = rf(idEspacio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bloque_tiempo.BloqueTiempo)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idEspacio)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBloqueTiempoRepository creates a new instance of BloqueTiempoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBloqueTiempoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BloqueTiempoRepository {
	mock := &BloqueTiempoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
