// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	cuenta "github.com/MervanXD/backend_ClubYa/internal/models/cuenta"
	mock "github.com/stretchr/testify/mock"
)

// CuentaRepository is an autogenerated mock type for the CuentaRepository type
type CuentaRepository struct {
	mock.Mock
}

// CrearCuenta provides a mock function with given fields: _a0
func (_m *CuentaRepository) CrearCuenta(_a0 cuenta.Cuenta) (int64, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CrearCuenta")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(cuenta.Cuenta) (int64, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(cuenta.Cuenta) int64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(cuenta.Cuenta) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogIn provides a mock function with given fields: _a0
func (_m *CuentaRepository) LogIn(_a0 cuenta.Cuenta) (cuenta.DTOCuenta, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for LogIn")
	}

	var r0 cuenta.DTOCuenta
	var r1 error
	if rf, ok := ret.Get(0).(func(cuenta.Cuenta) (cuenta.DTOCuenta, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(cuenta.Cuenta) cuenta.DTOCuenta); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(cuenta.DTOCuenta)
	}

	if rf, ok := ret.Get(1).(func(cuenta.Cuenta) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCuentaRepository creates a new instance of CuentaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCuentaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CuentaRepository {
	mock := &CuentaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
