// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	horario "github.com/MervanXD/backend_ClubYa/internal/models/horario"
	mock "github.com/stretchr/testify/mock"
)

// HorarioDiaRepository is an autogenerated mock type for the HorarioDiaRepository type
type HorarioDiaRepository struct {
	mock.Mock
}

// ObtenerBloquesTiempoEspacio provides a mock function with given fields: idEspacio, fecha
func (_m *HorarioDiaRepository) ObtenerBloquesTiempoEspacio(idEspacio int, fecha string) ([]horario.HorarioDiaDTO, error) {
	ret := _m.Called(idEspacio, fecha)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerBloquesTiempoEspacio")
	}

	var r0 []horario.HorarioDiaDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) ([]horario.HorarioDiaDTO, error)); ok {
		return rf(idEspacio, fecha)
	}
	if rf, ok := ret.Get(0).(func(int, string) []horario.HorarioDiaDTO); ok {
		r0 = rf(idEspacio, fecha)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]horario.HorarioDiaDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(idEspacio, fecha)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHorarioDiaRepository creates a new instance of HorarioDiaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHorarioDiaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HorarioDiaRepository {
	mock := &HorarioDiaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
