name: Deploy to EC2

on:
  push:
    branches:
      - despliegue

jobs:
  deploy:
    name: Deploy Backend to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-52-203-212-207.compute-1.amazonaws.com << 'EOF'
          cd /home/ubuntu/backend_ClubYa
          git pull origin despliegue
          sudo systemctl start docker
          sudo docker-compose down
          sudo docker-compose build
          sudo docker-compose up -d
        EOF
